#application: theairhorner
#version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "10s"
# [START handlers]
handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html

 - url: /(.*)
   static_files: build/\1
   upload: build/(.*)
# [END handlers]
skip_files:
- ^.tmp/.*
- ^app/.*
- ^jsqrcode/.*
- ^node_modules/.*
